mqtt:
  server: mqtt://core-mosquitto:1883
  base_topic: zigbee2mqtt_3
  version: 5
  user: addons
  password: UJ6xaJ5Xahfu4Aiy2queu9aip6Kiughie0eedei7Uv1Pheesh5euk9ieQuiePhah
serial:
  port: tcp://192.168.0.9:6638
  baudrate: 115200
  disable_led: false
advanced:
  transmit_power: 20
  channel: 20
  pan_id: 17891
  network_key:
    - 255
    - 143
    - 35
    - 118
    - 165
    - 55
    - 107
    - 34
    - 36
    - 2
    - 140
    - 67
    - 50
    - 171
    - 181
    - 26
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
  log_level: info
homeassistant: true
permit_join: false
frontend:
  port: 8099
devices:
  '0xa4c138b72a314e97':
    friendly_name: LR TV Strip
availability: true
